import minisql.common.endian as endian
import tests.support.testkit as test

function main(args)
  state = test.create()

  test.equal(state, endian.componentName(), "common.endian", "component identity")
  test.equal(state, endian.targetMilestone(), "M1", "target milestone")
  test.equal(state, endian.isImplemented(), true, "implementation marker")

  b = bytes(1, 0)
  test.equal(state, endian.writeU8(b, 0, 255), 1, "writeU8 next offset")
  test.equal(state, hex(b), "ff", "writeU8 golden")
  test.equal(state, endian.readU8(b, 0), 255, "readU8 golden")
  test.equal(state, endian.writeI8(b, 0, -2), 1, "writeI8 next offset")
  test.equal(state, hex(b), "fe", "writeI8 negative golden")
  test.equal(state, endian.readI8(b, 0), -2, "readI8 negative golden")
  endian.writeI8(b, 0, endian.MIN_I8)
  test.equal(state, hex(b), "80", "writeI8 minimum golden")
  test.equal(state, endian.readI8(b, 0), endian.MIN_I8, "readI8 minimum golden")
  endian.writeI8(b, 0, endian.MAX_I8)
  test.equal(state, hex(b), "7f", "writeI8 maximum golden")
  test.equal(state, endian.readI8(b, 0), endian.MAX_I8, "readI8 maximum golden")

  b = bytes(2, 0)
  test.equal(state, endian.writeU16LE(b, 0, 0x1234), 2, "writeU16LE next offset")
  test.equal(state, hex(b), "3412", "writeU16LE golden")
  test.equal(state, endian.readU16LE(b, 0), 0x1234, "readU16LE golden")
  test.equal(state, endian.writeU16BE(b, 0, 0x1234), 2, "writeU16BE next offset")
  test.equal(state, hex(b), "1234", "writeU16BE golden")
  test.equal(state, endian.readU16BE(b, 0), 0x1234, "readU16BE golden")
  endian.writeI16LE(b, 0, -2)
  test.equal(state, hex(b), "feff", "writeI16LE negative golden")
  test.equal(state, endian.readI16LE(b, 0), -2, "readI16LE negative golden")
  endian.writeI16BE(b, 0, -2)
  test.equal(state, hex(b), "fffe", "writeI16BE negative golden")
  test.equal(state, endian.readI16BE(b, 0), -2, "readI16BE negative golden")
  endian.writeI16LE(b, 0, endian.MIN_I16)
  test.equal(state, hex(b), "0080", "writeI16LE minimum golden")
  test.equal(state, endian.readI16LE(b, 0), endian.MIN_I16, "readI16LE minimum golden")
  endian.writeI16BE(b, 0, endian.MIN_I16)
  test.equal(state, hex(b), "8000", "writeI16BE minimum golden")
  test.equal(state, endian.readI16BE(b, 0), endian.MIN_I16, "readI16BE minimum golden")
  endian.writeI16LE(b, 0, endian.MAX_I16)
  test.equal(state, hex(b), "ff7f", "writeI16LE maximum golden")
  test.equal(state, endian.readI16LE(b, 0), endian.MAX_I16, "readI16LE maximum golden")
  endian.writeI16BE(b, 0, endian.MAX_I16)
  test.equal(state, hex(b), "7fff", "writeI16BE maximum golden")
  test.equal(state, endian.readI16BE(b, 0), endian.MAX_I16, "readI16BE maximum golden")

  b = bytes(4, 0)
  test.equal(state, endian.writeU32LE(b, 0, 0x89ABCDEF), 4, "writeU32LE next offset")
  test.equal(state, hex(b), "efcdab89", "writeU32LE golden")
  test.equal(state, endian.readU32LE(b, 0), 0x89ABCDEF, "readU32LE golden")
  test.equal(state, endian.writeU32BE(b, 0, 0x89ABCDEF), 4, "writeU32BE next offset")
  test.equal(state, hex(b), "89abcdef", "writeU32BE golden")
  test.equal(state, endian.readU32BE(b, 0), 0x89ABCDEF, "readU32BE golden")
  endian.writeI32LE(b, 0, endian.MIN_I32)
  test.equal(state, hex(b), "00000080", "writeI32LE minimum golden")
  test.equal(state, endian.readI32LE(b, 0), endian.MIN_I32, "readI32LE minimum golden")
  endian.writeI32BE(b, 0, endian.MIN_I32)
  test.equal(state, hex(b), "80000000", "writeI32BE minimum golden")
  test.equal(state, endian.readI32BE(b, 0), endian.MIN_I32, "readI32BE minimum golden")
  endian.writeI32LE(b, 0, endian.MAX_I32)
  test.equal(state, hex(b), "ffffff7f", "writeI32LE maximum golden")
  test.equal(state, endian.readI32LE(b, 0), endian.MAX_I32, "readI32LE maximum golden")
  endian.writeI32BE(b, 0, endian.MAX_I32)
  test.equal(state, hex(b), "7fffffff", "writeI32BE maximum golden")
  test.equal(state, endian.readI32BE(b, 0), endian.MAX_I32, "readI32BE maximum golden")
  endian.writeU32LE(b, 0, endian.MAX_U32)
  test.equal(state, hex(b), "ffffffff", "writeU32LE maximum golden")
  test.equal(state, endian.readU32LE(b, 0), endian.MAX_U32, "readU32LE maximum golden")

  words = endian.makeUInt64(0x01234567, 0x89ABCDEF)
  test.equal(state, words.high, 0x01234567, "makeUInt64 high")
  test.equal(state, words.low, 0x89ABCDEF, "makeUInt64 low")

  b = bytes(8, 0)
  test.equal(state, endian.writeU64LE(b, 0, words), 8, "writeU64LE next offset")
  test.equal(state, hex(b), "efcdab8967452301", "writeU64LE golden")
  readWords = endian.readU64LE(b, 0)
  test.equal(state, readWords.high, words.high, "readU64LE high")
  test.equal(state, readWords.low, words.low, "readU64LE low")
  test.equal(state, endian.writeU64BE(b, 0, words), 8, "writeU64BE next offset")
  test.equal(state, hex(b), "0123456789abcdef", "writeU64BE golden")
  readWords = endian.readU64BE(b, 0)
  test.equal(state, readWords.high, words.high, "readU64BE high")
  test.equal(state, readWords.low, words.low, "readU64BE low")

  maxWords = endian.makeUInt64(endian.MAX_U32, endian.MAX_U32)
  endian.writeU64LE(b, 0, maxWords)
  test.equal(state, hex(b), "ffffffffffffffff", "writeU64LE maximum golden")
  readWords = endian.readU64LE(b, 0)
  test.equal(state, readWords.high, endian.MAX_U32, "readU64LE maximum high")
  test.equal(state, readWords.low, endian.MAX_U32, "readU64LE maximum low")
  endian.writeU64BE(b, 0, maxWords)
  test.equal(state, hex(b), "ffffffffffffffff", "writeU64BE maximum golden")
  readWords = endian.readU64BE(b, 0)
  test.equal(state, readWords.high, endian.MAX_U32, "readU64BE maximum high")
  test.equal(state, readWords.low, endian.MAX_U32, "readU64BE maximum low")

  negativeTwo = endian.int64FromInt(-2)
  test.equal(state, negativeTwo.high, 0xFFFFFFFF, "int64FromInt negative high")
  test.equal(state, negativeTwo.low, 0xFFFFFFFE, "int64FromInt negative low")
  test.equal(state, endian.int64ToInt(negativeTwo), -2, "int64ToInt negative")
  test.equal(state, endian.int64IsNegative(negativeTwo), true, "negative sign detection")

  test.equal(state, endian.writeI64LE(b, 0, negativeTwo), 8, "writeI64LE next offset")
  test.equal(state, hex(b), "feffffffffffffff", "writeI64LE negative golden")
  readSigned = endian.readI64LE(b, 0)
  test.equal(state, readSigned.high, 0xFFFFFFFF, "readI64LE negative high")
  test.equal(state, readSigned.low, 0xFFFFFFFE, "readI64LE negative low")
  test.equal(state, endian.readI64AsIntLE(b, 0), -2, "readI64AsIntLE negative")
  test.equal(state, endian.writeI64BE(b, 0, negativeTwo), 8, "writeI64BE next offset")
  test.equal(state, hex(b), "fffffffffffffffe", "writeI64BE negative golden")
  readSigned = endian.readI64BE(b, 0)
  test.equal(state, readSigned.high, 0xFFFFFFFF, "readI64BE negative high")
  test.equal(state, readSigned.low, 0xFFFFFFFE, "readI64BE negative low")
  test.equal(state, endian.readI64AsIntBE(b, 0), -2, "readI64AsIntBE negative")

  minimum = endian.minInt64()
  test.equal(state, minimum.high, 0x80000000, "minimum I64 high")
  test.equal(state, minimum.low, 0, "minimum I64 low")
  test.equal(state, endian.int64IsNegative(minimum), true, "minimum I64 is negative")
  endian.writeI64LE(b, 0, minimum)
  test.equal(state, hex(b), "0000000000000080", "writeI64LE minimum golden")
  readSigned = endian.readI64LE(b, 0)
  test.equal(state, readSigned.high, 0x80000000, "readI64LE minimum high")
  test.equal(state, readSigned.low, 0, "readI64LE minimum low")
  endian.writeI64BE(b, 0, minimum)
  test.equal(state, hex(b), "8000000000000000", "writeI64BE minimum golden")
  readSigned = endian.readI64BE(b, 0)
  test.equal(state, readSigned.high, 0x80000000, "readI64BE minimum high")
  test.equal(state, readSigned.low, 0, "readI64BE minimum low")

  maximum = endian.maxInt64()
  test.equal(state, maximum.high, 0x7FFFFFFF, "maximum I64 high")
  test.equal(state, maximum.low, 0xFFFFFFFF, "maximum I64 low")
  test.equal(state, endian.int64IsNegative(maximum), false, "maximum I64 is positive")
  endian.writeI64LE(b, 0, maximum)
  test.equal(state, hex(b), "ffffffffffffff7f", "writeI64LE maximum golden")
  readSigned = endian.readI64LE(b, 0)
  test.equal(state, readSigned.high, 0x7FFFFFFF, "readI64LE maximum high")
  test.equal(state, readSigned.low, 0xFFFFFFFF, "readI64LE maximum low")
  endian.writeI64BE(b, 0, maximum)
  test.equal(state, hex(b), "7fffffffffffffff", "writeI64BE maximum golden")
  readSigned = endian.readI64BE(b, 0)
  test.equal(state, readSigned.high, 0x7FFFFFFF, "readI64BE maximum high")
  test.equal(state, readSigned.low, 0xFFFFFFFF, "readI64BE maximum low")

  positive = 0x0123456789ABCDEF
  positiveWords = endian.int64FromInt(positive)
  test.equal(state, positiveWords.high, 0x01234567, "int64FromInt positive high")
  test.equal(state, positiveWords.low, 0x89ABCDEF, "int64FromInt positive low")
  test.equal(state, endian.int64ToInt(positiveWords), positive, "int64ToInt positive")
  test.equal(state, endian.int64IsNegative(positiveWords), false, "positive sign detection")

  scalarMaxWords = endian.uint64FromInt(endian.MAX_MINILANG_INT)
  test.equal(state, scalarMaxWords.high, 0x0FFFFFFF, "uint64FromInt scalar max high")
  test.equal(state, scalarMaxWords.low, 0xFFFFFFFF, "uint64FromInt scalar max low")
  test.equal(state, endian.uint64ToInt(scalarMaxWords), endian.MAX_MINILANG_INT, "uint64ToInt scalar max")
  test.equal(state, endian.uint64Equals(words, endian.makeUInt64(0x01234567, 0x89ABCDEF)), true, "uint64Equals true")
  test.equal(state, endian.uint64Equals(words, endian.makeUInt64(0x01234567, 0x89ABCDEE)), false, "uint64Equals false")

  signedScalarMax = endian.int64FromInt(endian.MAX_MINILANG_INT)
  test.equal(state, signedScalarMax.high, 0x0FFFFFFF, "signed scalar max high")
  test.equal(state, signedScalarMax.low, 0xFFFFFFFF, "signed scalar max low")
  test.equal(state, endian.int64ToInt(signedScalarMax), endian.MAX_MINILANG_INT, "signed scalar max conversion")
  signedScalarMin = endian.int64FromInt(endian.MIN_MINILANG_INT)
  test.equal(state, signedScalarMin.high, 0xF0000000, "signed scalar min high")
  test.equal(state, signedScalarMin.low, 0, "signed scalar min low")
  test.equal(state, endian.int64ToInt(signedScalarMin), endian.MIN_MINILANG_INT, "signed scalar min conversion")

  asSignedBits = endian.uint64BitsToInt64(words)
  test.equal(state, asSignedBits.high, words.high, "U64 to I64 bit conversion high")
  test.equal(state, asSignedBits.low, words.low, "U64 to I64 bit conversion low")
  asUnsignedBits = endian.int64BitsToUInt64(asSignedBits)
  test.equal(state, asUnsignedBits.high, words.high, "I64 to U64 bit conversion high")
  test.equal(state, asUnsignedBits.low, words.low, "I64 to U64 bit conversion low")
  test.equal(state, endian.int64Equals(asSignedBits, endian.makeInt64(0x01234567, 0x89ABCDEF)), true, "int64Equals true")
  test.equal(state, endian.int64Equals(asSignedBits, endian.makeInt64(0x01234567, 0x89ABCDEE)), false, "int64Equals false")

  b = bytes(20, 0xCC)
  offset = 1
  offset = endian.writeU8(b, offset, 0x11)
  offset = endian.writeU16LE(b, offset, 0x2233)
  offset = endian.writeU32BE(b, offset, 0x44556677)
  offset = endian.writeI64FromIntLE(b, offset, -2)
  test.equal(state, offset, 16, "sequential write cursor")
  test.equal(state, hex(b), "cc11332244556677feffffffffffffffcccccccc", "sequential mixed layout")

  test.verifyChecks(state, 118, "m1_endian_golden.ml check count")

  return test.finish(
    state,
    "MiniSQL M1R1 endian golden tests: SUCCESS",
    "MiniSQL M1R1 endian golden tests: FAIL"
  )
end function
